### PR TITLE
Gkjh/#55#64

### PR DESCRIPTION
**Pull request by garrythezany**
Hello again!

As suggested, I've closed the old pull-request. Excuse me for the long delay 
but finally I found the time to wrap it up, hopefully now is everything as desired.

To answer your question, I'd say I'm working in the hosting sector. :)

And again thanks for your time!

Garret

### CODE REVIEW

**Review by funkyfuture — CHANGES_REQUESTED** [review]
please just keep adding (atomic) commits here, it's easier for the review process. i'll squash them together later. descriptive commit messages and amendments to `HISTORY.rst` would be great.

**Comment by garrythezany** [comment]
Hello!

I fixed / added lines to the tests as desired, but I wasn't possible for me to force the `monkeypatch` to actively set the `JOB_NAME_REGEX` in another test - now the total cover is <90% and I won't have the time to fix this (I'm not reeaaally a python-dev).

Thanks for your time!

Garret

**Comment by funkyfuture** [comment]
okay, i figured that testing for regex patterns that would allow dots isn't possible concisely. please watch this repo and handle all issues that stem from a misconfiguration of job name patterns! ;-)

**Comment by funkyfuture** [comment]
These changes have been merged as 05072fe9c71038468d16870d0020e924dbc3dff2 and 8891a586f79f8ae18ac8e850cb3f9c89a02dc17f.

**Pull request closed without merging**
